### ISSUE TITLE
Where Can I put ".ckpt " model?

### ISSUE THREAD

**Issue by bluesealjs** [sdbds/champ-for-windows#1]
hello, I am new to AI. I have SD `v1-5-pruned-emaonly.ckpt`, where can I put this file ? 

```
Use local model
Add loading local safetensors or ckpt,you can change config/prompts/animation.yaml about pretrained_weights for your local SD1.5 model. such as "D:\\stablediffusion-webui\\models\\Stable-diffusion\\v1-5-pruned.ckpt"
```

I get following errors

```
Some weights of the model checkpoint were not used when initializing UNet2DConditionModel:                                                                
'conv_norm_out.weight, conv_norm_out.bias, conv_out.weight, conv_out.bias']                                                                            
03/26/2024 02:43:02 - INFO - models.unet_3d - loaded temporal unet's pretrained weights from 
pretrained_models\stable-diffusion-v1-5\unet ...            Traceback (most recent call last):                                                                                                                         
File "W:\my-business\Qode-Houzz-Products\my make-memory-ai\champ-for-windows\inference.py", line 290, in 
<module>                                          main(cfg)                                                                                                                                              
File "W:\my-business\Qode-Houzz-Products\my make-memory-ai\champ-for-windows\inference.py", line 179, in main                                              
denoising_unet = UNet3DConditionModel.from_pretrained_2d(                                                                                              
File "W:\my-business\Qode-Houzz-Products\my make-memory-ai\champ-for-windows\models\unet_3d.py", line 662, in 
from_pretrained_2d                           raise FileNotFoundError(f"no weights file found in {pretrained_model_path}")                                                                         
FileNotFoundError: no weights file found in pretrained_models\stable-diffusion-v1-5\unet 
```

**Comment by sdbds** [comment]
sorry i forgot update this.
change
`configs/inference.yaml`

with `base_model_path`

**Comment by JPW0080** [comment]
On my side, 2 other issues cropped up.

Edit \champ-for-windows\models\unet_3d.py
Find         elif str(pretrained_model_path).endswith(".ckpt"): 

Just below, change weights_only=True, > weights_only=False,

Command Prompt:
\champ-for-windows\venv\Scripts\activate.bat

pip install pytorch_lightning

cd \champ-for-windows

python inference.py --config configs/inference.yaml

**Comment by sdbds** [comment]
Fixed bug now
