### ISSUE TITLE
FileNotFoundError: no weights file found in pretrained_models\stable-diffusion-v1-5\unet

### ISSUE THREAD

**Issue by ultimatech-cn** [sdbds/champ-for-windows#2]
Installation finished, when inference , got following error:

```
03/27/2024 09:33:28 - INFO - root - Running inference ...
tokenizer/vocab.json: 1.06MB [00:00, 1.57MB/s]
tokenizer/merges.txt: 525kB [00:00, 2.68MB/s]
tokenizer/special_tokens_map.json: 100%|██████████████████████████████████████████████████████████████████████████████████████████████| 472/472 [00:00<?, ?B/s]
tokenizer/tokenizer_config.json: 806B [00:00, ?B/s]
Some weights of the model checkpoint were not used when initializing UNet2DConditionModel:
 ['conv_norm_out.weight, conv_norm_out.bias, conv_out.weight, conv_out.bias']
03/27/2024 09:33:41 - INFO - models.unet_3d - loaded temporal unet's pretrained weights from pretrained_models\stable-diffusion-v1-5\unet ...
Traceback (most recent call last):
  File "E:\dev\champ-for-windows\inference.py", line 290, in <module>
    main(cfg)
  File "E:\dev\champ-for-windows\inference.py", line 179, in main
    denoising_unet = UNet3DConditionModel.from_pretrained_2d(
  File "E:\dev\champ-for-windows\models\unet_3d.py", line 662, in from_pretrained_2d
    raise FileNotFoundError(f"no weights file found in {pretrained_model_path}")
FileNotFoundError: no weights file found in pretrained_models\stable-diffusion-v1-5\unet
```
The files in "pretrained_models\stable-diffusion-v1-5\unet" folder
<img width="854" alt="1711504088949" src="https://github.com/sdbds/champ-for-windows/assets/142652112/762a3eb9-def0-4a05-9e4d-98e34536bb87">

Any solution for this?

**Comment by sdbds** [comment]
fix it now, i just forget to load original bin

**Comment by ultimatech-cn** [comment]
How to fix it? Download the repo again or the model?

**Comment by ultimatech-cn** [comment]
I download the updated python code. It works.
